# metadata specialised for each experiment
core:
  version: 0.0.1
  tags:
    - maml

model:
  net:
    num_classes: 5


defaults:
  - data: mini_imagenet
  - model: maml
  - optim: default
  - train: default
  - hydra: default
  - _self_
